#!/usr/bin/perl
use strict;
use warnings;

#my @months= ("January","February","March","April","May","June","July","August","September","October","November","December");
my @months= qw(January February March April May June July August September October November December);



foreach my $i(1){
  print "Year:$i\n";
    foreach my $j(1..12){
        if ($j=~/[135789]/||$j=10||$j=12){
         print "---$months[$j-1]---\n";
             foreach my $k(1..31){
              print "  $k ";
              }}
              print "\n";
           } print "\n\n";
        }

